# Generated by Django 6.0.4 on 2026-04-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.CharField(default='default.png', max_length=200),
        ),
    ]
