# Generated by Django 6.0.4 on 2026-04-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.CharField(default='default.png', max_length=200),
        ),
    ]
